/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_lanan_filetransport_utils_Jni */

#ifndef _Included_com_lanan_filetransport_utils_Jni
#define _Included_com_lanan_filetransport_utils_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lanan_filetransport_utils_Jni
 * Method:    server_set_socket
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lanan_filetransport_utils_Jni_server_1set_1socket
        (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_lanan_filetransport_utils_Jni
 * Method:    set_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lanan_filetransport_utils_Jni_set_1stop
        (JNIEnv *, jobject);

/*
 * Class:     com_lanan_filetransport_utils_Jni
 * Method:    client_send_file
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lanan_filetransport_utils_Jni_client_1send_1file
        (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

#define TAG "Emilio"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)

#ifdef __cplusplus
}
#endif
#endif
